package com.example.JPADemo.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.JPADemo.model.User;
import com.example.JPADemo.repository.UserRepository;

// TO specify that this class, managed by Spring
// Is of type service

@Service
public class UserService {
	
	@Autowired // Spring will take care of the creation, injection and destroy
	private UserRepository userRepository;
	
	// C
	public User saveUser(User user) {
		// THE INSERT into method generated by JPA
		return userRepository.save(user);
	}
	
	// R
	public List<User> getAllUsers(){
		// THE SELECT * methods generate by JPA
		return userRepository.findAll();
	}
	
	// D
	
	public void deleteUser(Long id) {
		// The DELETE FROM ... methods generated by JPA
		userRepository.deleteById(id);
	}
	
	public List<User> findUsersByName(String name){
		// Calling custom method 
		return userRepository.findByNameContaining(name);
	}
	
	
	public List<User> findUsersByAgeGreaterThan(int age){
		// Calling custom method created by JPA
		return userRepository.findByAgeGreaterThan(age);
	}
	
	

}
